import express from 'express';
import morgan from 'morgan';
import cors from 'cors';
import config from './config/config.js';
import userRoutes from './routes/user.route.js';
import tipoDocumentoRoutes from './routes/tipoDocumento.route.js';
import temaPrincipalRoutes from './routes/temaPrincipal.route.js';
import remitentesRoutes from './routes/remitente.route.js';
import rolRoutes from './routes/rol.route.js';
import documentoRoutes from './routes/documento.route.js';
import adicionalRoutes from './routes/adicional.route.js';
import areaRoutes from './routes/area.route.js';
import instruccionRoutes from './routes/instruccion.route.js';
await import('./config/db.js');
const app = express();
app.set('port', config.PORT);
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
const api = config.API_URL;
app.use(`${api}/users`, userRoutes);
app.use(`${api}/tipoDocumento`, tipoDocumentoRoutes);
app.use(`${api}/temaPrincipal`, temaPrincipalRoutes);
app.use(`${api}/remitentes`, remitentesRoutes);
app.use(`${api}/roles`, rolRoutes);
app.use(`${api}/documentos`, documentoRoutes);
app.use(`${api}/adicional`, adicionalRoutes);
app.use(`${api}/areas`, areaRoutes);
app.use(`${api}/instruccion`, instruccionRoutes);
console.log(`API URL: ${api}` + `, PORT: ${config.PORT}`);

export default app;